# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\PRO\china_wind_acc_python2.7_eric4\wac_sh.ui'
#
# Created: Thu Oct 17 00:07:18 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_acc_sh(object):
    def setupUi(self, acc_sh):
        acc_sh.setObjectName(_fromUtf8("acc_sh"))
        acc_sh.resize(438, 519)
        acc_sh.setStyleSheet(_fromUtf8(""))
        self.verticalLayoutWidget = QtGui.QWidget(acc_sh)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 164, 411))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lb_us = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_us.setObjectName(_fromUtf8("lb_us"))
        self.verticalLayout.addWidget(self.lb_us)
        self.lb_hft_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_hft_3.setObjectName(_fromUtf8("lb_hft_3"))
        self.verticalLayout.addWidget(self.lb_hft_3)
        self.lb_w = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_w.setObjectName(_fromUtf8("lb_w"))
        self.verticalLayout.addWidget(self.lb_w)
        self.lb_xi = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_xi.setObjectName(_fromUtf8("lb_xi"))
        self.verticalLayout.addWidget(self.lb_xi)
        self.lb_nu = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_nu.setObjectName(_fromUtf8("lb_nu"))
        self.verticalLayout.addWidget(self.lb_nu)
        self.lb_h = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_h.setObjectName(_fromUtf8("lb_h"))
        self.verticalLayout.addWidget(self.lb_h)
        self.lb_b = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_b.setObjectName(_fromUtf8("lb_b"))
        self.verticalLayout.addWidget(self.lb_b)
        self.lb_l = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_l.setObjectName(_fromUtf8("lb_l"))
        self.verticalLayout.addWidget(self.lb_l)
        self.lb_m = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_m.setObjectName(_fromUtf8("lb_m"))
        self.verticalLayout.addWidget(self.lb_m)
        self.lb_ccd = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_ccd.setObjectName(_fromUtf8("lb_ccd"))
        self.verticalLayout.addWidget(self.lb_ccd)
        self.lb_hfznb = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_hfznb.setObjectName(_fromUtf8("lb_hfznb"))
        self.verticalLayout.addWidget(self.lb_hfznb)
        self.lb_hft = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_hft.setObjectName(_fromUtf8("lb_hft"))
        self.verticalLayout.addWidget(self.lb_hft)
        self.lb_hft_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.lb_hft_2.setObjectName(_fromUtf8("lb_hft_2"))
        self.verticalLayout.addWidget(self.lb_hft_2)
        self.verticalLayoutWidget_2 = QtGui.QWidget(acc_sh)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 0, 81, 421))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.le_us = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_us.setObjectName(_fromUtf8("le_us"))
        self.verticalLayout_2.addWidget(self.le_us)
        self.le_w0 = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_w0.setObjectName(_fromUtf8("le_w0"))
        self.verticalLayout_2.addWidget(self.le_w0)
        self.le_w = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_w.setObjectName(_fromUtf8("le_w"))
        self.verticalLayout_2.addWidget(self.le_w)
        self.le_xi = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_xi.setObjectName(_fromUtf8("le_xi"))
        self.verticalLayout_2.addWidget(self.le_xi)
        self.le_nu = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_nu.setObjectName(_fromUtf8("le_nu"))
        self.verticalLayout_2.addWidget(self.le_nu)
        self.le_h = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_h.setObjectName(_fromUtf8("le_h"))
        self.verticalLayout_2.addWidget(self.le_h)
        self.le_b = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_b.setObjectName(_fromUtf8("le_b"))
        self.verticalLayout_2.addWidget(self.le_b)
        self.le_l = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_l.setObjectName(_fromUtf8("le_l"))
        self.verticalLayout_2.addWidget(self.le_l)
        self.le_m = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_m.setObjectName(_fromUtf8("le_m"))
        self.verticalLayout_2.addWidget(self.le_m)
        self.cb_ccd = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.cb_ccd.setObjectName(_fromUtf8("cb_ccd"))
        self.cb_ccd.addItem(_fromUtf8(""))
        self.cb_ccd.addItem(_fromUtf8(""))
        self.cb_ccd.addItem(_fromUtf8(""))
        self.cb_ccd.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.cb_ccd)
        self.le_hfznb = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_hfznb.setObjectName(_fromUtf8("le_hfznb"))
        self.verticalLayout_2.addWidget(self.le_hfznb)
        self.le_hft = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_hft.setObjectName(_fromUtf8("le_hft"))
        self.verticalLayout_2.addWidget(self.le_hft)
        self.le_beta = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.le_beta.setObjectName(_fromUtf8("le_beta"))
        self.verticalLayout_2.addWidget(self.le_beta)
        self.le_sf = QtGui.QLineEdit(acc_sh)
        self.le_sf.setGeometry(QtCore.QRect(140, 430, 81, 20))
        self.le_sf.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.le_sf.setObjectName(_fromUtf8("le_sf"))
        self.lb_sf = QtGui.QLabel(acc_sh)
        self.lb_sf.setGeometry(QtCore.QRect(10, 430, 121, 20))
        self.lb_sf.setObjectName(_fromUtf8("lb_sf"))
        self.btnyes = QtGui.QPushButton(acc_sh)
        self.btnyes.setGeometry(QtCore.QRect(140, 490, 81, 21))
        self.btnyes.setObjectName(_fromUtf8("btnyes"))
        self.lb_hf = QtGui.QLabel(acc_sh)
        self.lb_hf.setGeometry(QtCore.QRect(10, 460, 121, 20))
        self.lb_hf.setObjectName(_fromUtf8("lb_hf"))
        self.le_hf = QtGui.QLineEdit(acc_sh)
        self.le_hf.setGeometry(QtCore.QRect(140, 460, 81, 20))
        self.le_hf.setStyleSheet(_fromUtf8("background-color: rgb(0, 255, 0);"))
        self.le_hf.setObjectName(_fromUtf8("le_hf"))
        self.label = QtGui.QLabel(acc_sh)
        self.label.setGeometry(QtCore.QRect(10, 490, 111, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.pte_h = QtGui.QPlainTextEdit(acc_sh)
        self.pte_h.setGeometry(QtCore.QRect(290, 50, 51, 461))
        self.pte_h.setObjectName(_fromUtf8("pte_h"))
        self.pte_m = QtGui.QPlainTextEdit(acc_sh)
        self.pte_m.setGeometry(QtCore.QRect(370, 50, 51, 461))
        self.pte_m.setObjectName(_fromUtf8("pte_m"))
        self.label_3 = QtGui.QLabel(acc_sh)
        self.label_3.setGeometry(QtCore.QRect(370, 30, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(acc_sh)
        self.label_4.setGeometry(QtCore.QRect(280, 30, 91, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))

        self.retranslateUi(acc_sh)
        QtCore.QMetaObject.connectSlotsByName(acc_sh)

    def retranslateUi(self, acc_sh):
        acc_sh.setWindowTitle(_translate("acc_sh", "风作用顶点最大加速度计算", None))
        self.lb_us.setText(_translate("acc_sh", "体型系数u_s", None))
        self.lb_hft_3.setText(_translate("acc_sh", "基本风压w0", None))
        self.lb_w.setText(_translate("acc_sh", "10年重现期风压w(kn/m^2)", None))
        self.lb_xi.setText(_translate("acc_sh", "脉动增大系数xi", None))
        self.lb_nu.setText(_translate("acc_sh", "脉动影响系数nu", None))
        self.lb_h.setText(_translate("acc_sh", "建筑物高度H", None))
        self.lb_b.setText(_translate("acc_sh", "建筑物迎风宽度B", None))
        self.lb_l.setText(_translate("acc_sh", "建筑物顺风向长度L", None))
        self.lb_m.setText(_translate("acc_sh", "建筑物总质量(t)", None))
        self.lb_ccd.setText(_translate("acc_sh", "地面粗糙度类别", None))
        self.lb_hfznb.setText(_translate("acc_sh", "横风向一阶结构阻尼比zata_s1", None))
        self.lb_hft.setText(_translate("acc_sh", "横风向第一自振周期T_1(s)", None))
        self.lb_hft_2.setText(_translate("acc_sh", "横风向一阶振型指数beta", None))
        self.cb_ccd.setItemText(0, _translate("acc_sh", "A", None))
        self.cb_ccd.setItemText(1, _translate("acc_sh", "B", None))
        self.cb_ccd.setItemText(2, _translate("acc_sh", "C", None))
        self.cb_ccd.setItemText(3, _translate("acc_sh", "D", None))
        self.lb_sf.setText(_translate("acc_sh", "顺风向顶点最大加速度", None))
        self.btnyes.setText(_translate("acc_sh", "确定", None))
        self.lb_hf.setText(_translate("acc_sh", "横风向顶点最大加速度", None))
        self.label.setText(_translate("acc_sh", "计算过程见shacc.txt", None))
        self.label_3.setText(_translate("acc_sh", "各层质量(t)", None))
        self.label_4.setText(_translate("acc_sh", "各层标高(m)", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    acc_sh = QtGui.QDialog()
    ui = Ui_acc_sh()
    ui.setupUi(acc_sh)
    acc_sh.show()
    sys.exit(app.exec_())

